services:
  - type: web
    name: ushika-csv-app
    env: python
    pythonVersion: "3.11.10"
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.10"